(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "cheatsheet")
(depends-on "crosshairs")
(depends-on "evil")
(depends-on "gruvbox-theme")
(depends-on "powerline")
(depends-on "smart-mode-line")
(depends-on "smart-mode-line-powerline-theme")
(depends-on "xclip")
