(source gnu)
(source melpa)

(depends-on "auto-complete")
(depends-on "cask")
(depends-on "cheatsheet")
(depends-on "cider")
(depends-on "crosshairs")
(depends-on "evil")
(depends-on "gruvbox-theme")
(depends-on "magit")
(depends-on "powerline")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "smart-mode-line")
(depends-on "smart-mode-line-powerline-theme")
(depends-on "xclip")
